language: bash
sudo: required
# Test on Xenial (16.04 LTS)
dist: xenial
# Only Ubuntu LTS distro supported by Travis-CI with packages for jq, shellcheck
# Source: https://pkgs.org/search/shellcheck

before_install:
  - git clone --depth 1 https://github.com/sstephenson/bats
  - cd bats && ./install.sh "${HOME}/.local" && cd .. && rm -rf bats
  - git clone --depth 1 https://github.com/ztombol/bats-support ../bats-support
before_script:
  - export PATH="${HOME}/.local/bin:${PATH}"
script:
  - sudo -E ${HOME}/.local/bin/bats test
